services:
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    networks:
      - app_network

  backend:
    build: ./backend
    ports:
      - "8000"
    depends_on:
      - redis
    networks:
      - app_network
    environment:
      - REDIS_BROKER=redis://redis:6379/0
      - REDIS_BACKEND=redis://redis:6379/0

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - redis
    networks:
      - app_network

  worker:
    build: backend
    command: celery -A app.celery.celery_app worker --loglevel=info
    network_mode: "host"
    depends_on:
      - redis
    environment:
      - REDIS_BROKER=redis://127.0.0.1:6380/0
      - REDIS_BACKEND=redis://127.0.0.1:6380/0

networks:
  app_network:
    driver: bridge
