"""Create TemporaryCode

Revision ID: 17b3f7d1c7ca
Revises: caa2d2cef811
Create Date: 2026-05-11 12:24:22.153170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17b3f7d1c7ca'
down_revision: Union[str, Sequence[str], None] = 'caa2d2cef811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporary_code',
    sa.Column('temporary_code_id', sa.Integer(), nullable=False),
    sa.Column('temporary_code_value', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('temporary_code_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_temporary_code_temporary_code_id'), 'temporary_code', ['temporary_code_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temporary_code_temporary_code_id'), table_name='temporary_code')
    op.drop_table('temporary_code')
    # ### end Alembic commands ###
