"""Create user

Revision ID: 2fceb213c2bb
Revises: 
Create Date: 2026-05-11 12:22:31.964277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fceb213c2bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temporary_code_temporary_code_id'), table_name='temporary_code')
    op.drop_table('temporary_code')
    op.drop_table('media')
    op.drop_table('comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('comment_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('comment_user_id_fkey')),
    sa.PrimaryKeyConstraint('comment_id', name=op.f('comment_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('comment_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('media',
    sa.Column('media_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('s3_key', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.comment_id'], name=op.f('media_comment_id_fkey')),
    sa.PrimaryKeyConstraint('media_id', name=op.f('media_pkey')),
    sa.UniqueConstraint('comment_id', name=op.f('media_comment_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('s3_key', name=op.f('media_s3_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('temporary_code',
    sa.Column('temporary_code_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('temporary_code_value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('temporary_code_user_id_fkey')),
    sa.PrimaryKeyConstraint('temporary_code_id', name=op.f('temporary_code_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('temporary_code_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_temporary_code_temporary_code_id'), 'temporary_code', ['temporary_code_id'], unique=False)
    # ### end Alembic commands ###
