name: Code Formatting Check

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  format:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install python dependencies
        run: pip install -r backend/requirements.txt

      - name: Create .env file
        run: |
          cat << EOF > backend/.env
            DB_USER=user
            DB_PASSWORD=password
            DB_NAME=nmae
            SMTP_USER=email
            SMTP_PASSWORD=password
            SMTP_HOST=host
            SMTP_PORT=0
            USER_USERNAME=user
            USER_PASSWORD=password
            REDIS_BROKER=url
            REDIS_BACKEND=url
            REDIS_CLIENT=url
            REDIS_SESSIONS=url
            ALGORITHM=HS256
            SECRET_KEY=key
            SECRET_SALT_KEY=test
            FRONTEND_URL=http://localhost
            S3_ACCESS_KEY=access_key
            S3_SECRET_KEY=secret_key
            S3_ENDPOINT=url
            S3_REGION=region
            S3_BUCKET=bucket
            IS_TESTING=True
          EOF

      - name: Code Formatting Check
        run: black --diff --check  backend/app/

      - name: Run pytest
        run: pytest backend/tests/
