name: Code Formatting Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  format:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies JavaScript
        run: |
          cd frontend
          npm ci
      
      - name: Check formatting with Prettier JavaScript
        run: |
          cd frontend
          npx prettier --check "src/**/*.{js,jsx,ts,tsx,json}" --config ./config_data/.prettierrc
          
          

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install python dependencies
        run: pip install -r backend/requirements.txt

      - name: Create .env file
        run: |
          cat << EOF > backend/.env
          DB_USER=user
          DB_PASSWORD=user_password
          DB_NAME=database_name
          SMTP_USER=email
          SMTP_PASSWORD=password
          SMTP_HOST=host
          SMTP_PORT=0
          FRONTEND_URL=url
          IS_PROD=false
          EOF

      - name: Run pytest
        run: pytest backend/tests/
